2025-06-01 12:23:20.928 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 12:23:30.317 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:182 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 12:23:38.388 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 12:23:40.344 | ERROR    | hcaptcha_challenger.agent.challenger:_solve_captcha:864 - ChallengeException - type=image_drag_single err=FileNotFoundError('Could not load image from tmp\\.challenge\\image_drag_drop\\Ρlease drag the shape on the right to its missing position in the pattern\\20250601\\20250601122338427858\\20250601122338427858_0_challenge_view.png')
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 151, in <module>
    main()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 147, in main
    app()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\main.py", line 324, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\core.py", line 757, in main
    return _main(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\core.py", line 195, in _main
    rv = self.invoke(ctx)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\main.py", line 699, in wrapper
    return callback(**use_params)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 143, in collect
    asyncio.run(run_collector())
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 141, in run_collector
    await startup_epic_awesome_gamer(page)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 131, in startup_epic_awesome_gamer
    await agent.collect_epic_games()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\collector.py", line 111, in collect_epic_games
    if not await self.epic_games.authorize(self.page):
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\epic_games.py", line 239, in authorize
    return await self._authorize(page)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\epic_games.py", line 194, in _authorize
    await agent.wait_for_challenge()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 874, in wait_for_challenge
    await asyncio.wait_for(self._solve_captcha(), timeout=self.config.EXECUTION_TIMEOUT)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 510, in wait_for
    return await fut
> File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 844, in _solve_captcha
    return await self.robotic_arm.challenge_image_drag_drop(challenge_type)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 587, in challenge_image_drag_drop
    raw, projection = await self._capture_spatial_mapping(frame_challenge, cache_key, cid)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 465, in _capture_spatial_mapping
    result = create_coordinate_grid(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\helper\create_coordinate_grid.py", line 138, in create_coordinate_grid
    raise FileNotFoundError(f"Could not load image from {image}")
FileNotFoundError: Could not load image from tmp\.challenge\image_drag_drop\Ρlease drag the shape on the right to its missing position in the pattern\20250601\20250601122338427858\20250601122338427858_0_challenge_view.png
2025-06-01 12:23:45.398 | WARNING  | epic_awesome_gamer.epic_games:_authorize:197 - Failed to solve captcha - 'NoneType' object is not subscriptable
2025-06-01 12:25:46.455 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 12:25:52.381 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:182 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 12:25:57.380 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 12:26:06.080 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 12:26:13.047 | WARNING  | hcaptcha_challenger.tools.spatial_path_reasoning:<lambda>:107 - Retry request (1/2) - Wait 3 seconds - Exception: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerMinute-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_requests_per_model_per_day', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel'}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerDay-FreeTier', 'quotaDimensions': {'model': 'gemini-2.0-pro-exp', 'location': 'global'}}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '57s'}]}}
2025-06-01 12:26:19.359 | WARNING  | hcaptcha_challenger.tools.spatial_path_reasoning:<lambda>:107 - Retry request (2/2) - Wait 3 seconds - Exception: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerMinute-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_requests_per_model_per_day', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel'}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerDay-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '51s'}]}}
2025-06-01 12:26:25.202 | ERROR    | hcaptcha_challenger.agent.challenger:_solve_captcha:864 - ChallengeException - type=image_drag_single err=RetryError(<Future at 0x228ea3c62d0 state=finished raised ClientError>)
Traceback (most recent call last):
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\asyncio\__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\tools\spatial_path_reasoning.py", line 169, in invoke_async
    self._response = await client.aio.models.generate_content(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\google\genai\models.py", line 7453, in generate_content
    response = await self._generate_content(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\google\genai\models.py", line 6447, in _generate_content
    response_dict = await self._api_client.async_request(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\google\genai\_api_client.py", line 799, in async_request
    result = await self._async_request(http_request=http_request, stream=False)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\google\genai\_api_client.py", line 743, in _async_request
    await errors.APIError.raise_for_async_response(response)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\google\genai\errors.py", line 129, in raise_for_async_response
    raise ClientError(status_code, response_json, response)
google.genai.errors.ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_requests_per_model_per_day', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel'}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.0-pro-exp', 'location': 'global'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerDay-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerMinute-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-pro-exp'}}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '45s'}]}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 151, in <module>
    main()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 147, in main
    app()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\main.py", line 324, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\core.py", line 757, in main
    return _main(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\core.py", line 195, in _main
    rv = self.invoke(ctx)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\main.py", line 699, in wrapper
    return callback(**use_params)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 143, in collect
    asyncio.run(run_collector())
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 141, in run_collector
    await startup_epic_awesome_gamer(page)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 131, in startup_epic_awesome_gamer
    await agent.collect_epic_games()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\collector.py", line 111, in collect_epic_games
    if not await self.epic_games.authorize(self.page):
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\epic_games.py", line 239, in authorize
    return await self._authorize(page)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\epic_games.py", line 194, in _authorize
    await agent.wait_for_challenge()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 874, in wait_for_challenge
    await asyncio.wait_for(self._solve_captcha(), timeout=self.config.EXECUTION_TIMEOUT)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 510, in wait_for
    return await fut
> File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 844, in _solve_captcha
    return await self.robotic_arm.challenge_image_drag_drop(challenge_type)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 591, in challenge_image_drag_drop
    response = await self._spatial_path_reasoner.invoke_async(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\asyncio\__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\asyncio\__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\__init__.py", line 421, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x228ea3c62d0 state=finished raised ClientError>]
2025-06-01 12:26:30.274 | WARNING  | epic_awesome_gamer.epic_games:_authorize:197 - Failed to solve captcha - 'NoneType' object is not subscriptable
2025-06-01 12:31:55.970 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 12:32:03.943 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:182 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 12:32:13.208 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_label_single_select count=2
2025-06-01 12:32:22.393 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_select:626 - [1/2]ToolInvokeMessage: {
  "Challenge Prompt": "Please click on the shape with the fewest holes",
  "Coordinates": "[{'x': 580, 'y': 680}]"
}
2025-06-01 12:32:35.106 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_select:626 - [2/2]ToolInvokeMessage: {
  "Challenge Prompt": "Please click on the shape with the fewest holes",
  "Coordinates": "[{'x': 640, 'y': 530}]"
}
2025-06-01 12:32:39.496 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 12:32:40.009 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 12:32:43.962 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 12:32:58.697 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 940, 'y': 465}, 'to': {'x': 750, 'y': 720}}]"
}
2025-06-01 12:33:04.086 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 12:33:06.052 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 12:33:10.434 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_label_single_select count=2
2025-06-01 12:33:19.036 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_select:626 - [1/2]ToolInvokeMessage: {
  "Challenge Prompt": "Please click on the shape with the fewest holes",
  "Coordinates": "[{'x': 600, 'y': 650}]"
}
2025-06-01 12:33:32.185 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_select:626 - [2/2]ToolInvokeMessage: {
  "Challenge Prompt": "Please click on the shape with the fewest holes",
  "Coordinates": "[{'x': 620, 'y': 520}]"
}
2025-06-01 12:33:36.497 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 12:33:37.777 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 12:33:42.630 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 3 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=496027, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': 'Dragon T...3d467c839449ab6ab52e7f'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 12:33:43.388 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 12:33:43.388 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 12:33:51.009 | DEBUG    | epic_awesome_gamer.epic_games:add_promotion_to_cart:124 - 🙌 Add to the shopping cart - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 12:33:56.601 | DEBUG    | epic_awesome_gamer.epic_games:add_promotion_to_cart:124 - 🙌 Add to the shopping cart - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 12:33:59.165 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:208 - Move ALL paid games from the shopping cart out
2025-06-01 12:34:03.870 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: Page.evaluate: "btoa" is read-only
SMBf@debugger eval code line 313 > eval:2:190298
@debugger eval code line 313 > eval:2:871603
evaluate@debugger eval code:313:29
@debugger eval code:1:44

2025-06-01 12:34:05.630 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:222 - Move to webPurchaseContainer iframe
2025-06-01 12:34:09.886 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:224 - Click payment button
2025-06-01 12:34:15.510 | WARNING  | hcaptcha_challenger.agent.challenger:_review_challenge_type:796 - Unknown request_type: request_type=''
2025-06-01 12:34:16.570 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 12:34:16.571 | WARNING  | epic_awesome_gamer.epic_games:_purchase_free_game:231 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 12:34:51.900 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 12:34:54.948 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 12:34:54.949 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:246 - ✅ All week-free games are already in the library
2025-06-01 12:34:54.949 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 12:41:05.047 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 12:41:05.780 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 12:41:05.780 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 12:41:11.149 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 12:41:14.508 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 12:41:14.508 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:246 - ✅ All week-free games are already in the library
2025-06-01 12:41:14.509 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 12:42:51.347 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 12:42:51.979 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 12:42:51.980 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 12:42:57.439 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 12:43:00.652 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 12:43:00.652 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:246 - ✅ All week-free games are already in the library
2025-06-01 12:43:00.653 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 13:26:01.927 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 13:26:02.776 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 13:26:02.777 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 13:26:07.902 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 13:26:10.889 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 13:26:10.890 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:282 - ✅ All week-free games are already in the library
2025-06-01 13:26:10.890 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 13:29:27.689 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 13:29:28.486 | ERROR    | epic_awesome_gamer.epic_games:collect_for_all_accounts:306 - ❌ Нет аккаунтов для обработки
2025-06-01 13:29:28.487 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:118 - ✅ Работа завершена
2025-06-01 13:32:05.473 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 13:32:06.095 | ERROR    | epic_awesome_gamer.epic_games:collect_for_all_accounts:306 - ❌ Нет аккаунтов для обработки
2025-06-01 13:32:06.096 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:118 - ✅ Работа завершена
2025-06-01 13:33:14.146 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 13:33:14.710 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 13:33:14.711 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 13:33:19.931 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 13:33:22.938 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 13:33:22.939 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:282 - ✅ All week-free games are already in the library
2025-06-01 13:33:22.940 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 13:35:25.853 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 13:35:26.694 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 13:35:26.694 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 13:35:31.933 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 13:35:35.192 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 13:35:35.192 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:284 - ✅ All week-free games are already in the library
2025-06-01 13:35:35.193 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 13:37:06.030 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 13:40:19.987 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 13:40:28.047 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 13:40:35.162 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:40:42.826 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 13:41:02.916 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1045, 'y': 465}, 'to': {'x': 718, 'y': 692}}]"
}
2025-06-01 13:41:08.203 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:41:09.242 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 13:41:12.577 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:41:20.597 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 13:41:40.731 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1035, 'y': 470}, 'to': {'x': 914, 'y': 624}}]"
}
2025-06-01 13:41:46.007 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:41:49.355 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 13:41:53.893 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:42:02.371 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 13:42:18.407 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1035, 'y': 480}, 'to': {'x': 855, 'y': 635}}]"
}
2025-06-01 13:42:23.679 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:42:27.033 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 13:42:31.031 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:42:39.529 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 13:42:53.190 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1035, 'y': 485}, 'to': {'x': 660, 'y': 500}}]"
}
2025-06-01 13:42:58.447 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:43:00.655 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 13:43:06.008 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:43:15.031 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 13:43:26.352 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1040, 'y': 470}, 'to': {'x': 920, 'y': 510}}]"
}
2025-06-01 13:43:31.581 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:43:34.102 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 13:43:37.379 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:43:45.759 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 13:43:54.629 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1040, 'y': 465}, 'to': {'x': 870, 'y': 450}}]"
}
2025-06-01 13:43:59.874 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:44:01.585 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 13:45:09.731 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 13:45:18.035 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 13:45:25.572 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:45:34.767 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 13:45:46.103 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1120, 'y': 490}, 'to': {'x': 1000, 'y': 700}}]"
}
2025-06-01 13:45:51.386 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:45:52.326 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 13:45:55.551 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:46:03.974 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 13:46:15.784 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1100, 'y': 500}, 'to': {'x': 840, 'y': 620}}]"
}
2025-06-01 13:46:21.081 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:46:24.301 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:46:51.084 | ERROR    | hcaptcha_challenger.agent.challenger:wait_for_challenge:889 - Wait for captcha response timeout 30.0s
2025-06-01 13:48:17.022 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 13:48:28.027 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 13:48:34.999 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 13:48:37.901 | ERROR    | hcaptcha_challenger.agent.challenger:_solve_captcha:864 - ChallengeException - type=image_drag_single err=FileNotFoundError('Could not load image from tmp\\.challenge\\image_drag_drop\\Ρlease drag the shape on the right to its missing position in the pattern\\20250601\\20250601134835998013\\20250601134835998013_0_challenge_view.png')
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 158, in <module>
    main()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 154, in main
    app()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\main.py", line 324, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\core.py", line 757, in main
    return _main(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\core.py", line 195, in _main
    rv = self.invoke(ctx)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\main.py", line 699, in wrapper
    return callback(**use_params)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 150, in collect
    asyncio.run(run_collector())
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 148, in run_collector
    await startup_epic_awesome_gamer(page)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 137, in startup_epic_awesome_gamer
    await agent.collect_epic_games()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\collector.py", line 111, in collect_epic_games
    if not await self.epic_games.authorize(self.page):
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\epic_games.py", line 246, in authorize
    return await self._authorize(page)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\epic_games.py", line 199, in _authorize
    await agent.wait_for_challenge()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 874, in wait_for_challenge
    await asyncio.wait_for(self._solve_captcha(), timeout=self.config.EXECUTION_TIMEOUT)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 510, in wait_for
    return await fut
> File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 844, in _solve_captcha
    return await self.robotic_arm.challenge_image_drag_drop(challenge_type)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 587, in challenge_image_drag_drop
    raw, projection = await self._capture_spatial_mapping(frame_challenge, cache_key, cid)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\agent\challenger.py", line 465, in _capture_spatial_mapping
    result = create_coordinate_grid(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\hcaptcha_challenger\helper\create_coordinate_grid.py", line 138, in create_coordinate_grid
    raise FileNotFoundError(f"Could not load image from {image}")
FileNotFoundError: Could not load image from tmp\.challenge\image_drag_drop\Ρlease drag the shape on the right to its missing position in the pattern\20250601\20250601134835998013\20250601134835998013_0_challenge_view.png
2025-06-01 13:48:42.961 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object is not subscriptable
2025-06-01 13:50:52.469 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 13:51:01.757 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 13:51:06.804 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:51:21.289 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_label_single_select count=None
2025-06-01 13:51:33.306 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_select:626 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'x': 1020, 'y': 555}]"
}
2025-06-01 13:51:37.596 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:51:40.703 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:52:07.614 | ERROR    | hcaptcha_challenger.agent.challenger:wait_for_challenge:889 - Wait for captcha response timeout 30.0s
2025-06-01 13:53:41.999 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 13:53:51.795 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 13:53:57.996 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:53:59.558 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 13:53:59.559 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 13:54:06.809 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 13:54:10.187 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 13:54:41.977 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 800, 'y': 460}, 'to': {'x': 800, 'y': 530}}]"
}
2025-06-01 13:54:47.247 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:54:47.957 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 13:54:53.633 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 13:55:03.436 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 795, 'y': 477}, 'to': {'x': 456, 'y': 477}}]"
}
2025-06-01 13:55:08.670 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 13:55:10.659 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 13:55:17.437 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 13:55:18.462 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 13:55:18.463 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 13:55:23.862 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 13:55:27.430 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 13:55:27.431 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:284 - ✅ All week-free games are already in the library
2025-06-01 13:55:27.431 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 13:56:23.312 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 13:56:32.617 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 13:56:41.113 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 13:56:42.677 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 13:56:42.677 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 14:00:04.347 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 14:00:14.105 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:00:20.512 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:00:22.068 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 14:00:22.068 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 14:00:29.604 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:00:33.662 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 14:00:46.395 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 900, 'y': 350}, 'to': {'x': 520, 'y': 360}}]"
}
2025-06-01 14:00:51.611 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:00:52.866 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:00:58.201 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 14:01:19.745 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 922, 'y': 338}, 'to': {'x': 690, 'y': 304}}]"
}
2025-06-01 14:01:24.977 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:01:27.094 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:01:33.081 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 14:01:44.927 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 920, 'y': 350}, 'to': {'x': 520, 'y': 405}}]"
}
2025-06-01 14:01:50.201 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:01:51.421 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:01:57.281 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 14:02:12.929 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 922, 'y': 338}, 'to': {'x': 779, 'y': 430}}]"
}
2025-06-01 14:02:18.163 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:02:21.206 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:02:25.311 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 14:02:39.310 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 922, 'y': 349}, 'to': {'x': 743, 'y': 553}}]"
}
2025-06-01 14:02:44.555 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:02:45.780 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:02:49.743 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 14:03:01.815 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 910, 'y': 360}, 'to': {'x': 820, 'y': 370}}]"
}
2025-06-01 14:03:07.044 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:03:08.290 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:03:10.067 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - Page.wait_for_timeout: Target page, context or browser has been closed
2025-06-01 14:06:52.346 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 14:07:02.274 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:07:10.906 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:07:12.484 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 14:07:12.485 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 14:07:19.556 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:07:25.537 | WARNING  | hcaptcha_challenger.agent.challenger:_review_challenge_type:796 - Unknown request_type: request_type=''
2025-06-01 14:07:26.585 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 14:07:26.585 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 14:07:31.585 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: Page.evaluate: "btoa" is read-only
SXQn@debugger eval code line 313 > eval:2:195098
@debugger eval code line 313 > eval:2:873126
evaluate@debugger eval code:313:29
@debugger eval code:1:44

2025-06-01 14:10:09.487 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:10:10.471 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:10:10.472 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:10:16.079 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:10:19.274 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:10:19.274 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:284 - ✅ All week-free games are already in the library
2025-06-01 14:10:19.275 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:25:01.643 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 14:25:10.984 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:25:16.396 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:25:26.019 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 14:25:40.888 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1150, 'y': 470}, 'to': {'x': 930, 'y': 520}}]"
}
2025-06-01 14:25:46.125 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:25:47.390 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 14:25:53.935 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:25:55.214 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:25:55.215 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:26:00.799 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:26:04.036 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:26:04.037 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:284 - ✅ All week-free games are already in the library
2025-06-01 14:26:04.038 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:26:12.961 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 14:26:21.959 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:26:28.122 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:26:29.692 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 14:26:29.692 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 14:26:36.360 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:26:44.182 | WARNING  | hcaptcha_challenger.agent.challenger:_review_challenge_type:796 - Unknown request_type: request_type=''
2025-06-01 14:26:45.230 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 14:26:45.231 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 14:26:50.700 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: Page.evaluate: "btoa" is read-only
SXQn@debugger eval code line 313 > eval:2:195098
@debugger eval code line 313 > eval:2:873126
evaluate@debugger eval code:313:29
@debugger eval code:1:44

2025-06-01 14:31:11.824 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:31:12.737 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:31:12.738 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:31:18.106 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:31:21.304 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:105 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:31:21.305 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:284 - ✅ All week-free games are already in the library
2025-06-01 14:31:21.305 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:31:30.619 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 14:31:40.567 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:31:46.147 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:31:47.727 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 14:31:47.728 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 14:31:52.679 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: : Protocol error (Network.getResponseBody): Component returned failure code: 0x804b001b (NS_ERROR_INVALID_CONTENT_ENCODING) [nsIStreamListener.onDataAvailable]
2025-06-01 14:31:53.125 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:187 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:31:57.093 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:31:57.094 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:31:58.673 | ERROR    | hcaptcha_challenger.agent.challenger:get_challenge_frame_locator:318 - Cannot find a valid challenge frame
2025-06-01 14:31:58.673 | WARNING  | epic_awesome_gamer.epic_games:_authorize:202 - Failed to solve captcha - 'NoneType' object has no attribute 'locator'
2025-06-01 14:32:03.333 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: : Protocol error (Network.getResponseBody): Component returned failure code: 0x804b001b (NS_ERROR_INVALID_CONTENT_ENCODING) [nsIStreamListener.onDataAvailable]
2025-06-01 14:32:03.333 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: : Protocol error (Network.getResponseBody): Component returned failure code: 0x804b001b (NS_ERROR_INVALID_CONTENT_ENCODING) [nsIStreamListener.onDataAvailable]
2025-06-01 14:33:38.123 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:33:39.059 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:33:39.060 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:33:43.880 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:33:46.877 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:33:46.878 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 14:33:46.879 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:33:56.173 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 14:34:06.339 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:188 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 14:34:19.236 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:34:31.348 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 14:34:42.692 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1010, 'y': 450}, 'to': {'x': 796, 'y': 499}}]"
}
2025-06-01 14:34:47.997 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:34:48.700 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:34:53.124 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:35:02.659 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 14:35:12.133 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1025, 'y': 455}, 'to': {'x': 725, 'y': 475}}]"
}
2025-06-01 14:35:17.393 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:35:20.673 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 14:35:27.666 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:35:27.666 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:36:09.599 | DEBUG    | epic_awesome_gamer.epic_games:add_promotion_to_cart:125 - 🙌 Add to the shopping cart - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:36:15.519 | DEBUG    | epic_awesome_gamer.epic_games:add_promotion_to_cart:125 - 🙌 Add to the shopping cart - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:36:18.056 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:257 - Move ALL paid games from the shopping cart out
2025-06-01 14:36:23.750 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: : Protocol error (Network.getResponseBody): Component returned failure code: 0x804b001b (NS_ERROR_INVALID_CONTENT_ENCODING) [nsIStreamListener.onDataAvailable]
2025-06-01 14:36:23.751 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: : Protocol error (Network.getResponseBody): Component returned failure code: 0x804b001b (NS_ERROR_INVALID_CONTENT_ENCODING) [nsIStreamListener.onDataAvailable]
2025-06-01 14:36:49.124 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:271 - Move to webPurchaseContainer iframe
2025-06-01 14:36:53.235 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:273 - Click payment button
2025-06-01 14:36:56.236 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:36:56.237 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:37:08.001 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 14:37:39.915 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1000, 'y': 450}, 'to': {'x': 790, 'y': 412}}]"
}
2025-06-01 14:37:45.139 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:37:46.576 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:37:49.939 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:37:49.942 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 14:37:50.493 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: Page.evaluate: "btoa" is read-only
hopwM@debugger eval code line 313 > eval:2:190392
@debugger eval code line 313 > eval:2:871791
evaluate@debugger eval code:313:29
@debugger eval code:1:44

2025-06-01 14:37:54.438 | WARNING  | hcaptcha_challenger.tools.challenge_classifier:<lambda>:137 - Retry request (1/2) - Wait 3 seconds - Exception: [Errno 11004] getaddrinfo failed
2025-06-01 14:38:03.789 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 14:38:20.479 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1030, 'y': 439}, 'to': {'x': 743, 'y': 431}}]"
}
2025-06-01 14:38:25.712 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:38:26.512 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:38:28.533 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:38:28.534 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 14:38:31.069 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 14:38:31.382 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: Page.evaluate: "btoa" is read-only
ukHAlq@debugger eval code line 313 > eval:2:197473
@debugger eval code line 313 > eval:2:879756
evaluate@debugger eval code:313:29
@debugger eval code:1:44

2025-06-01 14:38:31.395 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: Page.evaluate: "btoa" is read-only
ukHAlq@debugger eval code line 313 > eval:2:197473
@debugger eval code line 313 > eval:2:879756
evaluate@debugger eval code:313:29
@debugger eval code:1:44

2025-06-01 14:38:43.493 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1000, 'y': 578}, 'to': {'x': 860, 'y': 485}}]"
}
2025-06-01 14:38:48.734 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 14:38:50.616 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 14:38:55.942 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:296 - 🎉 Successfully collected all weekly games
2025-06-01 14:38:55.942 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:42:24.365 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:42:25.262 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:42:25.263 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:42:30.310 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:42:33.393 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:42:33.393 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 14:42:33.394 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:42:46.248 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:42:46.670 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:42:46.670 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:42:51.479 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:42:54.513 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:42:54.513 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 14:42:54.514 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:47:31.830 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:47:32.993 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:47:32.994 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:47:34.662 | ERROR    | epic_awesome_gamer.collector:collect_epic_games:137 - Page.goto: Target page, context or browser has been closed
Call log:
  - navigating to "https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands", waiting until "load"

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 218, in <module>
    main()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 214, in main
    app()
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\main.py", line 324, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\core.py", line 757, in main
    return _main(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\core.py", line 195, in _main
    rv = self.invoke(ctx)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\typer\main.py", line 699, in wrapper
    return callback(**use_params)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 205, in collect
    asyncio.run(run_collector())
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 194, in run_collector
    await startup_epic_awesome_gamer(page, email, password)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\cli\main.py", line 150, in startup_epic_awesome_gamer
    await agent.collect_epic_games()
> File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\collector.py", line 135, in collect_epic_games
    await self.epic_games.collect_weekly_games(game_promotions)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\asyncio\__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\asyncio\__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\__init__.py", line 400, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\tenacity\asyncio\__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\epic_games.py", line 288, in collect_weekly_games
    if not await self.add_promotion_to_cart(self.page, urls):
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\src\epic_awesome_gamer\epic_games.py", line 90, in add_promotion_to_cart
    await page.goto(url, wait_until="load", timeout=29000)
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\playwright\async_api\_generated.py", line 8991, in goto
    await self._impl_obj.goto(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\playwright\_impl\_page.py", line 552, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Vlad\Downloads\epic-awesome-gamer-main\epic-awesome-gamer-main\venv\Lib\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed
Call log:
  - navigating to "https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands", waiting until "load"

2025-06-01 14:47:34.668 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:47:47.677 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:47:48.349 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:47:48.349 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:47:54.367 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:47:57.020 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:47:57.021 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 14:47:57.021 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:52:39.894 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:52:41.079 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:52:41.079 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:52:49.000 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:52:51.829 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:52:51.829 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 14:52:51.830 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:53:05.832 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 14:53:06.595 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 14:53:06.595 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 14:53:12.185 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 14:53:15.183 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 14:53:15.184 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 14:53:15.184 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 14:53:25.022 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 14:53:36.615 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:188 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 15:12:43.445 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 15:12:55.104 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:188 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 15:13:05.341 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:13:18.023 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:13:36.839 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1130, 'y': 470}, 'to': {'x': 830, 'y': 700}}]"
}
2025-06-01 15:13:42.181 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:13:43.430 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:13:47.476 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:13:56.852 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:14:16.597 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1100, 'y': 470}, 'to': {'x': 790, 'y': 535}}]"
}
2025-06-01 15:14:21.885 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:14:26.903 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:14:51.907 | ERROR    | hcaptcha_challenger.agent.challenger:wait_for_challenge:889 - Wait for captcha response timeout 30.0s
2025-06-01 15:15:33.507 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 15:15:45.375 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:188 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 15:15:59.561 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:16:09.208 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:16:23.138 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 935, 'y': 460}, 'to': {'x': 620, 'y': 670}}]"
}
2025-06-01 15:16:28.410 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:16:29.240 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:16:34.882 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:16:43.178 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:16:56.706 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 930, 'y': 470}, 'to': {'x': 550, 'y': 680}}]"
}
2025-06-01 15:17:02.009 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:17:03.913 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:17:09.391 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:17:09.960 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_label_binary count=None
2025-06-01 15:17:20.363 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_binary:557 - [1/2]ToolInvokeMessage: {
  "Challenge Prompt": "Choose all items with rotating components like the example shown",
  "Coordinates": "[[2, 0], [2, 1]]"
}
2025-06-01 15:17:34.314 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_binary:557 - [2/2]ToolInvokeMessage: {
  "Challenge Prompt": "Choose all items with rotating components like the example shown",
  "Coordinates": "[[1, 1], [2, 1], [2, 2]]"
}
2025-06-01 15:17:41.913 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:17:46.653 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 15:17:54.840 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 15:17:55.989 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 15:17:55.989 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 15:18:02.028 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 15:18:05.463 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 15:18:05.464 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 15:18:05.464 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 15:18:16.426 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 15:18:33.438 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:188 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 15:18:44.585 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:18:56.457 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:19:30.744 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 955, 'y': 460}, 'to': {'x': 630, 'y': 760}}]"
}
2025-06-01 15:19:41.269 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:19:43.152 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:19:49.825 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:20:03.425 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:20:17.841 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 945, 'y': 465}, 'to': {'x': 860, 'y': 690}}]"
}
2025-06-01 15:20:30.551 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:20:36.594 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:20:40.497 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:20:50.296 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:21:20.256 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 934, 'y': 487}, 'to': {'x': 585, 'y': 505}}]"
}
2025-06-01 15:21:26.173 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:21:28.688 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 15:22:18.863 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 15:22:28.763 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:188 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 15:22:40.460 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:22:51.888 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:23:01.634 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1147, 'y': 477}, 'to': {'x': 1004, 'y': 703}}]"
}
2025-06-01 15:23:06.939 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:23:08.145 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:23:13.265 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:23:23.956 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_label_single_select count=None
2025-06-01 15:23:33.168 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_select:626 - [1/2]ToolInvokeMessage: {
  "Challenge Prompt": "Please click on the shape with the fewest holes",
  "Coordinates": "[{'x': 960, 'y': 520}]"
}
2025-06-01 15:23:46.250 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_label_select:626 - [2/2]ToolInvokeMessage: {
  "Challenge Prompt": "Please click on the shape with the fewest holes",
  "Coordinates": "[{'x': 1000, 'y': 505}]"
}
2025-06-01 15:23:50.549 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:23:53.279 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 15:24:01.325 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 15:24:02.422 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 15:24:02.422 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 15:24:08.749 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 15:24:11.948 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 15:24:11.948 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 15:24:11.949 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 15:24:26.327 | WARNING  | epic_awesome_gamer.collector:_sync_order_history:62 - 5 validation errors for Order
items.0.amount
  Input should be a valid string [type=string_type, input_value=124900, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.0.price
  Field required [type=missing, input_value={'description': "Tiny Tin...cc4969a57b6b1bdc28af4a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
items.1.amount
  Input should be a valid string [type=string_type, input_value=22500, input_type=int]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
items.1.price
  Field required [type=missing, input_value={'description': 'Limbo', ...8e4aa9b1ad413f72090f5e'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
promotions.0.priceString
  Field required [type=missing, input_value={'type': 'PROMOTION_RULE'...cy': 'UAH', 'title': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-01 15:24:27.129 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 15:24:27.129 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 15:24:32.986 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 15:24:36.467 | SUCCESS  | epic_awesome_gamer.epic_games:add_promotion_to_cart:106 - ✅ Already in the library - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 15:24:36.468 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:289 - ✅ All week-free games are already in the library
2025-06-01 15:24:36.468 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
2025-06-01 15:24:46.299 | INFO     | epic_awesome_gamer.collector:collect_epic_games:110 - Try to flush cookie
2025-06-01 15:24:55.822 | DEBUG    | epic_awesome_gamer.epic_games:_authorize:188 - Login with Email - https://www.epicgames.com/id/login?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3Flang%3Den-US%26productName%3Degs%26sessionInvalidated%3Dtrue
2025-06-01 15:25:06.679 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:25:18.792 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:25:33.217 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1120, 'y': 475}, 'to': {'x': 980, 'y': 490}}]"
}
2025-06-01 15:25:38.456 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:25:41.517 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:25:46.393 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:25:56.794 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:26:11.912 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1146, 'y': 477}, 'to': {'x': 968, 'y': 477}}]"
}
2025-06-01 15:26:17.195 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:26:20.340 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:26:24.208 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:26:32.592 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:26:47.284 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1150, 'y': 470}, 'to': {'x': 825, 'y': 455}}]"
}
2025-06-01 15:26:52.563 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:26:56.690 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:27:00.550 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:27:09.835 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:27:20.178 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1120, 'y': 480}, 'to': {'x': 1000, 'y': 650}}]"
}
2025-06-01 15:27:25.428 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:27:26.839 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:27:32.915 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:27:42.179 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:27:52.705 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1135, 'y': 480}, 'to': {'x': 800, 'y': 480}}]"
}
2025-06-01 15:27:57.727 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:27:59.385 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:28:03.333 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:28:12.723 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:28:24.279 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1150, 'y': 460}, 'to': {'x': 968, 'y': 681}}]"
}
2025-06-01 15:28:30.058 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:28:34.252 | WARNING  | hcaptcha_challenger.agent.challenger:wait_for_challenge:895 - Failed to challenge, try to retry the strategy
2025-06-01 15:28:38.953 | WARNING  | hcaptcha_challenger.agent.challenger:_task_handler:742 - HSW reverse failed, fallback to regular processing
2025-06-01 15:28:48.697 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=None
2025-06-01 15:29:00.625 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1110, 'y': 470}, 'to': {'x': 790, 'y': 645}}]"
}
2025-06-01 15:29:05.964 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:29:07.037 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 15:29:21.939 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Tiny Tina's Wonderlands》 url=https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
2025-06-01 15:29:21.940 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:126 - ✅ Discover promotion《Limbo》 url=https://store.epicgames.com/en-US/p/limbo
2025-06-01 15:29:30.381 | DEBUG    | epic_awesome_gamer.epic_games:add_promotion_to_cart:125 - 🙌 Add to the shopping cart - url='https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands'
2025-06-01 15:29:36.216 | DEBUG    | epic_awesome_gamer.epic_games:add_promotion_to_cart:125 - 🙌 Add to the shopping cart - url='https://store.epicgames.com/en-US/p/limbo'
2025-06-01 15:29:38.629 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:257 - Move ALL paid games from the shopping cart out
2025-06-01 15:29:44.258 | ERROR    | hcaptcha_challenger.agent.challenger:_task_handler:686 - An error occurred while injecting hsw script: Page.evaluate: "btoa" is read-only
VWlGNF@debugger eval code line 313 > eval:2:204797
@debugger eval code line 313 > eval:2:887316
evaluate@debugger eval code:313:29
@debugger eval code:1:44

2025-06-01 15:30:09.812 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:271 - Move to webPurchaseContainer iframe
2025-06-01 15:30:13.938 | DEBUG    | epic_awesome_gamer.epic_games:_purchase_free_game:273 - Click payment button
2025-06-01 15:30:19.462 | DEBUG    | hcaptcha_challenger.agent.challenger:_solve_captcha:805 - Start Challenge - type=image_drag_single count=1
2025-06-01 15:30:31.958 | DEBUG    | hcaptcha_challenger.agent.challenger:challenge_image_drag_drop:596 - [1/1]ToolInvokeMessage: {
  "Challenge Prompt": "Please drag the shape on the right to its missing position in the pattern",
  "Coordinates": "[{'from': {'x': 1140, 'y': 490}, 'to': {'x': 800, 'y': 690}}]"
}
2025-06-01 15:30:37.286 | DEBUG    | hcaptcha_challenger.agent.challenger:wait_for_challenge:883 - Start checking captcha response
2025-06-01 15:30:40.579 | SUCCESS  | hcaptcha_challenger.agent.challenger:wait_for_challenge:901 - Challenge success
2025-06-01 15:30:45.373 | SUCCESS  | epic_awesome_gamer.epic_games:collect_weekly_games:296 - 🎉 Successfully collected all weekly games
2025-06-01 15:30:45.374 | DEBUG    | epic_awesome_gamer.collector:collect_epic_games:143 - ✅ Workflow ends
